name: Actividad Ingesta de Datos

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.2"
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate
      - name: paso3 - Instalar dependencias
        run: pip install -r requirements.txt
      - name: paso4 - Ejecutar el script de ingestión
        run: python src/ingestion.py
      - name: paso5 - Ejecutar el script de Preprocesamiento y Limpieza de Datos
        run: python src/simulacion_procesamiento.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Ejecutar el script de Preprocesamiento y Limpieza de Datos"
          commit_user_name: "Davinson Rincon [GitHub Actions]"
          commit_user_email: "davinson.rincon@est.iudigital.edu.co"
          commit_author: "Davinson Rincon <davinson.rincon@est.iudigital.edu.co>"
          push_options: '--force'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
