name: Data Ingestion Pipeline

on:
  # Ejecutar diariamente a medianoche
  schedule:
    - cron: "0 0 * * *"

  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  ingest_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories if not exist
        run: |
          mkdir -p src/static/auditoria
          mkdir -p src/static/db
          mkdir -p src/static/xlsx

      - name: Run ingestion script
        run: python src/ingestion.py

      - name: Verify files were created
        run: |
          if [ ! -f "src/static/db/ingestion.db" ]; then
            echo "Database file was not created!"
            exit 1
          fi
          if [ ! -f "src/static/xlsx/ingestion.xlsx" ]; then
            echo "Excel file was not created!"
            exit 1
          fi
          if [ ! -f "src/static/auditoria/ingestion.txt" ]; then
            echo "Audit file was not created!"
            exit 1
          fi

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/static/auditoria/ingestion.txt src/static/xlsx/ingestion.xlsx src/static/db/ingestion.db
          git commit -m "Update data files from automated ingestion" || echo "No changes to commit"
          git push

